### ISSUE TITLE
Couldn't push Docker Image when use with Swift as storage

### ISSUE THREAD

**Issue by winggundamth** [bacongobbler/docker-registry-driver-swift#22]
From https://github.com/docker/docker-registry/issues/724

I installed with these commands

```
apt-get install -y build-essential python-dev libevent-dev liblzma-dev redis-server libxml2-dev libxslt1-dev libyaml-dev libz-dev python-lxml git
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
pip install docker-registry
git clone https://github.com/bacongobbler/docker-registry-driver-swift.git src
pip install ./src
mkdir -p /docker-registry/registry
wget https://raw.githubusercontent.com/docker/docker-registry/master/config/config_sample.yml -O /docker-registry/config.yml
```

I use sample config.yml from docker-registry repo without any modification. And this is my environment configuration file

```
export SEARCH_BACKEND=sqlalchemy
export SQLALCHEMY_INDEX_DATABASE=sqlite:////docker-registry/docker-registry.db
export CACHE_REDIS_HOST=127.0.0.1
export CACHE_REDIS_PORT=6379
export CACHE_LRU_REDIS_HOST=127.0.0.1
export CACHE_LRU_REDIS_PORT=6379
export DOCKER_REGISTRY_CONFIG=/docker-registry/config.yml
export SETTINGS_FLAVOR=swift
export STORAGE_PATH=/registry
export OS_AUTH_URL=https://identity.example.com/v2.0
export OS_CONTAINER=registry
export OS_USERNAME=swiftuser
export OS_PASSWORD=swiftpass
export OS_TENANT_NAME=swift-registry
```

then I start everything with commands

```
service redis-server start
source /docker-registry/config-environment.sh
docker-registry
```

This is output

```
2014-11-14 02:56:12 [18363] [INFO] Starting gunicorn 19.1.0
2014-11-14 02:56:12 [18363] [INFO] Listening at: http://0.0.0.0:5000 (18363)
2014-11-14 02:56:12 [18363] [INFO] Using worker: gevent
2014-11-14 02:56:12 [18370] [INFO] Booting worker with pid: 18370
2014-11-14 02:56:12 [18371] [INFO] Booting worker with pid: 18371
2014-11-14 02:56:12 [18372] [INFO] Booting worker with pid: 18372
2014-11-14 02:56:12 [18377] [INFO] Booting worker with pid: 18377
2014-11-14 02:56:12 [18363] [INFO] 4 workers
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling lru cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling lru cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling lru cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling lru cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis lru host: 127.0.0.1:6379 (db0)
14/Nov/2014:02:56:12 +0000 INFO: Enabling storage cache on Redis
14/Nov/2014:02:56:12 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
```

Error output when I push something

```
14/Nov/2014:02:56:12 +0000 INFO: Redis config: {'path': '/registry', 'host': '127.0.0.1', 'password': None, 'db': 0, 'port': 6379}
14/Nov/2014:02:57:37 +0000 INFO: Starting new HTTPS connection (1): identity.example.com
14/Nov/2014:02:57:42 +0000 ERROR: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1200, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1174, in get_auth
    insecure=self.insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 371, in get_auth
    insecure=insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 308, in get_keystoneclient_2_0
    raise ClientException('Authorization Failure. %s' % err)
ClientException: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
14/Nov/2014:02:57:43 +0000 INFO: Starting new HTTPS connection (1): identity.example.com
14/Nov/2014:02:57:48 +0000 ERROR: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1200, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1174, in get_auth
    insecure=self.insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 371, in get_auth
    insecure=insecure)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 308, in get_keystoneclient_2_0
    raise ClientException('Authorization Failure. %s' % err)
ClientException: Authorization Failure. Authorization Failed: __init__() got an unexpected keyword argument 'server_hostname'
2014-11-14 02:57:48,157 ERROR: Exception on /v1/repositories/ubuntu/ [PUT]
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data_arg)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/core/lru.py", line 78, in wrapper
    return f(*args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 75, in put_content
    self.put_store(path, content)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 85, in put_store
    raise IOError("Could not put content: %s" % path)
IOError: Could not put content: registry/repositories/library/ubuntu/_index_images
14/Nov/2014:02:57:48 +0000 ERROR: Exception on /v1/repositories/ubuntu/ [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 98, in put_repository
    update_index_images(namespace, repository, flask.request.data)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/index.py", line 80, in update_index_images
    store.put_content(path, data_arg)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/core/lru.py", line 78, in wrapper
    return f(*args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 75, in put_content
    self.put_store(path, content)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/swift.py", line 85, in put_store
    raise IOError("Could not put content: %s" % path)
IOError: Could not put content: registry/repositories/library/ubuntu/_index_images
172.17.42.1 - - [14/Nov/2014:02:57:48 +0000] "PUT /v1/repositories/ubuntu/ HTTP/1.0" 500 291 "-" "docker/1.3.1 go/go1.3.3 git-commit/4e9bbfa kernel/3.16.0-25-generic os/linux arch/amd64"
```

**Comment by bacongobbler** [comment]
@winggundamth with your client exception, it looks like you sent an extra config value called `server_hostname` which is not a supported config option for the driver. I'd inspect your registry config and make sure it's all correct. 

Is there a specific reason why you need a `server_hostname` key?

**Comment by bacongobbler** [comment]
closing as @gierschv explained it quite nicely. It seems to be an issue with the provider using integers as the tenant name, which I don't think we can resolve here (unless someone made a patch to the swift client).
