### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by beef9999** [bacongobbler/docker-registry-driver-swift#28]
`
lientException: Object HEAD failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_inprogress 404 Not Found
27/Mar/2015:04:12:13 +0000 INFO: REQ: curl -i http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/repositories/library/redis/_private -I -H "X-Auth-Token: 63193407cd084d74a19291b64d9363e1"
27/Mar/2015:04:12:13 +0000 INFO: RESP STATUS: 404 Not Found
27/Mar/2015:04:12:13 +0000 INFO: RESP HEADERS: [('content-length', '0'), ('server', 'Tengine'), ('connection', 'keep-alive'), ('x-trans-id', 'tx5a4cc0472bc145dca9588-005514d89d'), ('date', 'Fri, 27 Mar 2015 04:12:13 GMT'), ('content-type', 'text/html; charset=UTF-8')]
27/Mar/2015:04:12:13 +0000 ERROR: Object HEAD failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/repositories/library/redis/_private 404 Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1208, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 874, in head_object
    http_response_content=body)
ClientException: Object HEAD failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/repositories/library/redis/_private 404 Not Found
27/Mar/2015:04:12:13 +0000 INFO: REQ: curl -i http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_checksum -X GET -H "X-Auth-Token: 63193407cd084d74a19291b64d9363e1"
27/Mar/2015:04:12:13 +0000 INFO: RESP STATUS: 404 Not Found
27/Mar/2015:04:12:13 +0000 INFO: RESP HEADERS: [('content-length', '70'), ('server', 'Tengine'), ('connection', 'keep-alive'), ('x-trans-id', 'tx8fcee89abe0d4f4b9341e-005514d89d'), ('date', 'Fri, 27 Mar 2015 04:12:13 GMT'), ('content-type', 'text/html; charset=UTF-8')]
27/Mar/2015:04:12:13 +0000 INFO: RESP BODY: <html><h1>Not Found</h1><p>The resource could not be found.</p></html>
27/Mar/2015:04:12:13 +0000 ERROR: Object GET failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_checksum 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1208, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 827, in get_object
    http_response_content=body)
ClientException: Object GET failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_checksum 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
10.128.131.125 - - [27/Mar/2015:04:12:13 +0000] "GET /v1/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/json HTTP/1.1" 200 1950 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.13.0-27-generic os/linux arch/amd64"
27/Mar/2015:04:12:13 +0000 INFO: Starting new HTTPS connection (1): index.docker.io
27/Mar/2015:04:12:18 +0000 INFO: REQ: curl -i http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba943e44850/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_inprogress -I -H "X-Auth-Token: 202d85d7547e4ac68b4e984844c20f0e"
27/Mar/2015:04:12:18 +0000 INFO: RESP STATUS: 404 Not Found
27/Mar/2015:04:12:18 +0000 INFO: RESP HEADERS: [('content-length', '0'), ('server', 'Tengine'), ('connection', 'keep-alive'), ('x-trans-id', 'tx2a0da3fa51794b7283f54-005514d8a2'), ('date', 'Fri, 27 Mar 2015 04:12:18 GMT'), ('content-type', 'text/html; charset=UTF-8')]
27/Mar/2015:04:12:18 +0000 ERROR: Object HEAD failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba943e44850/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_inprogress 404 Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1208, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 874, in head_object
    http_response_content=body)
ClientException: Object HEAD failed: http://mtmos.com:80/v1/mss_f6a0ab7ca116464383bbfba9/registry/registry/images/e03cdbcf651a1419dbbab76d3c2f02fe3d175ee70d5d5ce1a1c3b61e30edbc17/_inprogress 404 Not Found
`

**Comment by bacongobbler** [comment]
those 404s are not really an issue. See https://github.com/docker/docker-registry/issues/219
